commit
htmlacademy-adaptive/1756361-pink-24 pull request #8
Opened 2022-01-15 08:33 UTC by drmisssciurus

2022-01-16 18:51 UTC, pavel-nyukalo requested changes

2022-01-16 18:51 UTC, pavel-nyukalo commented on source/index.html
> +        <button class="main-nav__toggle main-nav--closed main-nav--nojs" type="button">
Модификаторы используются не на том блоке (`main-nav--closed` должен относиться к `main-nav`, но никак не к `main-nav__toggle`

2022-01-16 18:51 UTC, pavel-nyukalo commented on source/index.html
> +    <script>
Скрипты лучше писать в отдельных файлах, в своей папке `js`

2022-01-16 18:51 UTC, pavel-nyukalo commented on source/index.html
> +      navMain.classList.remove('main-nav--nojs');
Тут уже скрипт не сработает. Ты пытаешься удалить класс у `navMain`, но у него нет такого класса. Зато такой класс есть у `navToggle`

2022-01-16 18:51 UTC, pavel-nyukalo commented on source/index.html
> +    </script>
Думаю, можно пока отложить открытие/закрытие меню и сосредоточиться на том, чтобы доделать сайт до макетного вида. А потом уже можно будет и мень доработать

2022-01-19 10:39 UTC, pavel-nyukalo requested changes

2022-01-19 10:39 UTC, pavel-nyukalo commented on source/less/blocks/intro.less
> +.marketplace {
`marketplace` не в этом файле должен находиться

2022-01-19 10:40 UTC, pavel-nyukalo commented on source/less/blocks/intro.less
> +.marketplace {
И не проходят проверки

![image](https://user-images.githubusercontent.com/52506235/150114287-b2f58d73-2837-4e27-8252-ea90a6fe3293.png)

2022-01-24 19:03 UTC, pavel-nyukalo requested changes

2022-01-24 19:03 UTC, pavel-nyukalo commented on source/less/blocks/triangle.less
> +}
Здесь не получается потому что псевдоэлементам надо задавать свойство `content` это раз, а во-вторых картинка не подгрузится из-за неправильного пути

2022-01-24 19:03 UTC, pavel-nyukalo commented on source/less/blocks/intro.less
> +.marketplace {
Не исправила вот тут

2022-01-27 11:29 UTC, pavel-nyukalo requested changes

2022-01-27 11:29 UTC, pavel-nyukalo commented on source/less/blocks/price.less
> +}
Стилизация по тегам запрещена критерием

2022-01-27 11:29 UTC, pavel-nyukalo commented on source/less/blocks/triangle.less
> +  width: 600000px;
Вот это значение 😲

2022-01-27 11:29 UTC, pavel-nyukalo commented on source/less/blocks/triangle.less
> +  background-image: url("../img/triangle-map.png");
Высота картинки 123px, и она кладется фоном в прямоугольник 400 на 50px, тут надо либо фон масштабировать и вписывать, либо прямоугольник увеличивать

2022-01-27 11:29 UTC, pavel-nyukalo commented on source/less/blocks/advantages.less
> +  background-position: 50% -250px;
Здесь фон позиционируется не так как надо из-за `-250рх`

2022-01-27 12:45 UTC, drmisssciurus commented on source/index.html
> +                  <cite class="reviews__author-name">Николай Петров<span class="reviews__author-name--mobile">25 лет, водитель трамвая</span></cite>
reviews__author-info--mobile? так?

2022-01-27 12:47 UTC, drmisssciurus commented on source/index.html
> +              <th class="price__table--hidden"></th>
или так? price__table-item price__table-item--hidden

2022-01-31 07:01 UTC, pavel-nyukalo requested changes
Я посмотрел только мобильную версию, но при доработке проверь еще планшетку и десктоп

2022-02-02 19:20 UTC, merged